[project]
name = "dojo-cli"
version = "0.1.0"
description = "A command line interface wrapper for the pwn.college API"
readme = "README.md"
authors = [
    { name = "hidehiroanto", email = "hidehiro.anto@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "cairosvg>=2.9.0",
    "cyclopts>=4.23.2",
    "itsdangerous>=2.2.0",
    "mfusepy>=3.1.1",
    "mpv>=1.0.8",
    "niquests[ws]>=3.21.0",
    "paramiko>=5.0.0",
    "python-socketio[client]>=5.16.4",
    "pyyaml>=6.0.3",
    "textual-image>=0.13.2",
    "trogon>=0.6.0",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
dojo = "dojo_cli:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[tool.ruff]
line-length = 128

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
